apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  strategy:
    type: # TODO: Recreate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: hello
        image: ghcr.io/nginxdemos/hello:plain-text
        ports:
        - containerPort: 8080

# To trigger update and watch:
# kubectl set image deploy/api hello=ghcr.io/nginxdemos/hello:0.3-plain-text & kubectl get pods -l app=api -w
