apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: # TODO: nginx or http-echo
        ports:
        - containerPort: # TODO: 80 or 8080
        readinessProbe:
          httpGet:
            path: # TODO: /healthz
            port: # TODO: 80 or 8080
          initialDelaySeconds: # TODO: 5
          periodSeconds: # TODO: 5
        livenessProbe:
          httpGet:
            path: # TODO: /alive
            port: # TODO: 80 or 8080
          initialDelaySeconds: # TODO: 10
          periodSeconds: # TODO: 10
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: webapp
  ports:
  - port: 80
    targetPort: # TODO: 80 or 8080

# Note: With nginx, these probe paths will return 404 unless you configure them
# This is intentional to simulate failures
# You can exec into pod and create files:
# kubectl exec <pod> -- sh -c "mkdir -p /usr/share/nginx/html && echo 'OK' > /usr/share/nginx/html/healthz"
