# One-off Job
apiVersion: batch/v1
kind: Job
metadata:
  name: # TODO: job name
spec:
  template:
    spec:
      containers:
      - name: busybox
        image: # TODO: busybox:1.36
        command: # TODO: ["sh", "-c", "echo hello"]
      restartPolicy: # TODO: Never or OnFailure
---
# CronJob
apiVersion: batch/v1
kind: CronJob
metadata:
  name: # TODO: cronjob name
spec:
  schedule: # TODO: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: # TODO: busybox:1.36
            command: # TODO: ["sh", "-c", "date"]
          restartPolicy: # TODO: Never or OnFailure

# Quick create commands:
# kubectl create job hello-job --image=busybox:1.36 -- sh -c "echo hello"
# kubectl create cronjob date-cron --image=busybox:1.36 --schedule="*/2 * * * *" -- sh -c "date"
