# Blue Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      version: blue
  template:
    metadata:
      labels:
        app: api
        version: blue
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:1.0
        args: ["-text=Blue"]
        ports:
        - containerPort: 5678
---
# Green Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
      version: green
  template:
    metadata:
      labels:
        app: api
        version: green
    spec:
      containers:
      - name: http-echo
        image: hashicorp/http-echo:1.0
        args: ["-text=Green"]
        ports:
        - containerPort: 5678
---
# Service initially pointing to blue
apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api
    version: # TODO: initially blue, then change to green
  ports:
  - port: 8080
    targetPort: 5678

# To switch from blue to green:
# kubectl patch svc api-svc -p '{"spec":{"selector":{"version":"green"}}}'
